/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ['class'],
  content: [
    './pages/**/*.{js,jsx}',
    './components/**/*.{js,jsx}',
    './app/**/*.{js,jsx}',
    './src/**/*.{js,jsx}',
  ],
  theme: {
    extend: {
      fontSize: {
        8: '8px',
        10: '10px',
        11: '11px',
        12: '12px',
        14: '14px',
        15: '15px',
        16: '16px',
        18: '18px',
        20: '20px',
        22: '22px',
        24: '24px',
        25: '25px',
        26: '26px',
        28: '28px',
        30: '30px',
        32: '32px',
        36: '36px',
        42: '42px',
        46: '46px',
        48: '48px',
        56: '56px',
        60: '60px',
        64: '64px',
        76: '76px',
        80: '80px',
        90: '90px',
      },

      colors: {
        queueTxt: '#21383B',
        queueBlue: '#5456DE',
        queueBlueLighter: '#5444AB',
        queueBlack1: '#131517',
        queueLight1: '#fff',
        queueLightText1: '#000',
        queueDarkText1: '#fff',
        claimbtn: '#303030',
        primary: {
          90: '#707070',
          100: '#030b15',
          200: '#192431',
          300: '#6D5AE6',
          400: '#A2A2A2',
          500: '#FFFFFF',
          600: '#F4F4F4',
          700: '#ff9700',
          800: '#54EB9F',
          900: '#B1B1B5',
          1000: '#282B32',
          1100: '#21383B',
          1200: '#12d176',
          1300: '#0b1d33',
          1400: '#ADAEAF',
          1500: '#98999A',
          1600: '#AAA5A5',
          1700: '#F6F6F6',
          1800: '#22252B',
          para: '#a4b4c3',
          newborder: '#454546',
          border: '#121a23',
          lightGreen: '#A5E6C5',
          green: '#0A7E1A',
          greenLight: "#54EB9F",
          darkGray: '#1D1A17',
          light: '#F7F7F7',
          hoverBg: '#98999A',
          borderWhite: '#E4E5E5',
          orange: '#FFA500',
          red: '#E82121',
          lightBlue: '#968CFF',
        },
      },
      gradientColorStops: {
        'custom-gradient': ['#5456DE', '#230f38'],
      },

      backgroundImage: {
        'gradient-radial': 'radial-gradient(var(--tw-gradient-stops))',
        'gradient-conic':
          'conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))',
      },

      borderRadius: {
        partnerBox: '40%',
      },
      keyframes: {
        'accordion-down': {
          from: { height: 0 },
          to: { height: 'var(--radix-accordion-content-height)' },
        },
        'accordion-up': {
          from: { height: 'var(--radix-accordion-content-height)' },
          to: { height: 0 },
        },
        Anytime: {
          '2%,48%': { opacity: '100%' },
          '51%,100%': { opacity: '0%' },
        },
        Anywhere: {
          '51%,98%': { opacity: '100%' },
          '4%,48%': { opacity: '0%' },
        },
      },
      fontFamily: {
        brandon: ['Brandon', 'sans-serif'],
        brandonBold: ['BrandonBold', 'sans-serif'],
        brandonBlack: ['BrandonBlack', 'sans-serif'],
        lato: ['lato, brandon'],
        latothin: ['latothin'],
        latolight: ['latolight'],
        latoregular: ['latoregular'],
        latobold: ['latobold'],
        latoblack: ['latoblack'],
        brandonBoldItalic: 'brandonBoldItalic, sans-serif',
        brandonBlack: 'brandonBlack, sans-serif',
        brandonLight: 'brandonLight, sans-serif',
        brandonLightItalic: 'brandonLightItalic, sans-serif',
        brandonMediumItalic: 'brandonMediumItalic, sans-serif',
        brandonRegularItalic: 'brandonRegularItalic, sans-serif',
        brandonThinItalic: 'brandonThinItalic,sans-serif'
      },
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
        Anytime: 'Anytime 6s ease-in-out infinite',
        Anywhere: 'Anywhere 6s ease-in-out infinite',
      },
    },
    screens: {
      sm: '	640px',
      md: '768px',
      
      md2: '992px',
      lg: '1024px',
      xl: '1280px',
      xl2: '1366px',
      lg2: '1440px',
      '2xl': '1490px',
      '3xl': '1700px',
    },
    container: {
      center: true,
      padding: {
        DEFAULT: '1rem',
        sm: '2rem',
        lg: '2rem',
        md2: '2rem',
        xl2: '3rem',
        lg2: '3rem',
        xl: '3rem',
        '2xl': '2rem',
        '3xl': '2rem',
      },
    },
  },
  plugins: [require('tailwind-scrollbar'), require('tailwindcss-animate')],
};